name: docker_image-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: read

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
    - name: checkout4
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: run codeql
      run: date; pwd; ls; tag_version=1.0.0-$(date +"%Y%m%d%H%M%S"); tag_version
        
  docker_img_build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout4
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: install docker
      run: apt-get install -y docker

    - name: docker build
      run: docker build ./ -t django-lib:1.0
